In [1]:
from src.evaluation.comparison import compare_experiments

comparison = compare_experiments(
    ["logistic_unigram"]
)

comparison

              Model  Accuracy  Macro F1  Weighted F1
0  logistic_unigram   0.52682  0.241001     0.444378

In [2]:
comparison = compare_experiments(
    [
        "majority",
        "logistic_unigram",
        "svm_unigram",
    ]
)

comparison

              Model  Accuracy  Macro F1  Weighted F1
0       svm_unigram  0.505747  0.278811     0.459599
1  logistic_unigram  0.526820  0.241001     0.444378
2          majority  0.481226  0.092824     0.312685